## Group By and Aggregate Functions in Pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/Flavor.csv')
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [13]:
group_by_frame = df.groupby('Base Flavor')

In [14]:
group_by_frame.mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [16]:
df.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [17]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [19]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [20]:
df.groupby('Base Flavor').max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [22]:
df.groupby('Base Flavor').sum(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [25]:
df.groupby('Base Flavor').agg({'Flavor Rating': ['mean', 'sum', 'min', 'max', 'count']})

            Flavor Rating
                     mean   sum  min   max count
Base Flavor
Chocolate             8.4  25.2  8.2   8.8     3
Vanilla               5.7  34.2  2.3  10.0     6

In [27]:
df.groupby('Base Flavor').agg({
                                'Flavor Rating': ['mean', 'sum', 'min', 'max', 'count'],
                                'Texture Rating': ['mean', 'sum', 'min', 'max', 'count']
                              })

            Flavor Rating                        Texture Rating             \
                     mean   sum  min   max count           mean   sum  min
Base Flavor
Chocolate             8.4  25.2  8.2   8.8     3       7.233333  21.7  7.0
Vanilla               5.7  34.2  2.3  10.0     6       5.650000  33.9  3.4


             max count
Base Flavor
Chocolate    7.6     3
Vanilla      8.0     6

In [28]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [33]:
df.groupby(['Base Flavor', 'Liked']).agg({'Flavor Rating': ['mean', 'sum', 'min', 'max', 'count']})

                  Flavor Rating
                           mean   sum  min   max count
Base Flavor Liked
Chocolate   Yes             8.4  25.2  8.2   8.8     3
Vanilla     No              3.6  10.8  2.3   4.7     3
            Yes             7.8  23.4  6.5  10.0     3

In [36]:
df.groupby('Base Flavor').describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [37]:
df.groupby('Base Flavor').describe().T

Base Flavor           Chocolate    Vanilla
Flavor Rating  count   3.000000   6.000000
               mean    8.400000   5.700000
               std     0.346410   2.710719
               min     8.200000   2.300000
               25%     8.200000   4.025000
               50%     8.200000   5.600000
               75%     8.500000   6.800000
               max     8.800000  10.000000
Texture Rating count   3.000000   6.000000
               mean    7.233333   5.650000
               std     0.321455   1.566844
               min     7.000000   3.400000
               25%     7.050000   5.000000
               50%     7.100000   5.500000
               75%     7.350000   6.375000
               max     7.600000   8.000000
Total Rating   count   3.000000   6.000000
               mean   15.700000  11.350000
               std     0.781025   4.263684
               min    15.200000   5.700000
               25%    15.250000   9.025000
               50%    15.300000  11.100000
               75%    15.950000  13.175000
               max    16.600000  18.000000