# Merge, Join and Concatenate DataFrame

![merge_join_concatenate.jpg](data/merge_join_concatenate.jpg)

## Importing Libraries

In [1]:
import pandas as pd

## Loading Data

In [2]:
df1 = pd.read_csv('./data/lotr_1.csv')
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [3]:
df2 = pd.read_csv('./data/lotr_2.csv')
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

## Merge DataFrame

In [4]:
# Default how='inner'
df1.merge(df2)

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [5]:
# With how='inner'
df1.merge(df2, how='inner')

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [6]:
# With how='inner'
df1.merge(df2, how='inner', on='FellowshipID')

   FellowshipID FirstName_x     Skills FirstName_y  Age
0          1001       Frodo     Hiding       Frodo   50
1          1002     Samwise  Gardening     Samwise   39

In [8]:
# With how='inner'
df1.merge(df2, how='inner', on=['FellowshipID', 'FirstName'])

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [9]:
# With how='outer'
df1.merge(df2, how='outer')

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0